qlib_init:
    provider_uri: "data/qlib_data"
    region: cn
experiment_name: GRU_5ret_SimpleVixHandler_SimpleSignalStrategy
market: &market one_for_test
benchmark: &benchmark TLT
roll_config:
    step: 20
    horizon: 6
data_handler_config: &data_handler_config
    start_time: 2005-12-20
    end_time: 2022-08-15
    instruments: *market
    infer_processors:
        - class: BFill
          module_path: backtest.qlib_custom.processors
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
    label: ["Ref($close, -5) / $close - 1"]
port_analysis_config: &port_analysis_config
    strategy:
        class: SimpleSignalStrategy
        module_path: backtest.qlib_custom.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
    backtest:
        start_time: 2018-01-01
        end_time: 2022-12-15
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            deal_price: close
            open_cost: 0
            close_cost: 0
            min_cost: 0
task:
    model:
        class: GRU
        module_path: qlib.contrib.model.pytorch_gru_ts
        kwargs:
            d_feat: 15
            hidden_size: 64
            num_layers: 2
            dropout: 0.0
            n_epochs: 20
            lr: 1e-3
            early_stop: 10
            batch_size: 32
            metric: loss
            loss: mse
            n_jobs: 1
            GPU: 0
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: SimpleVixHandler
                module_path: backtest.qlib_custom.data_handler
                kwargs: *data_handler_config
            segments:
                train: [2005-12-20, 2011-12-31]
                valid: [2012-01-01, 2013-12-31]
                test: [2014-01-01, 2022-08-15]
    record:
        - class: ScoreSign
          module_path: backtest.qlib_custom.record
          kwargs:
            config: *port_analysis_config
