qlib_init:
    provider_uri: "data/qlib_data"
    region: us
market: &market one_for_test
benchmark: &benchmark TLT
data_handler_config: &data_handler_config
    start_time: 2005-12-20
    end_time: 2023-03-06
    fit_start_time: 2005-12-20
    fit_end_time: 2014-12-31
    instruments: *market
    feature_instruments: "features"
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: BFill
          module_path: backtest.qlib_custom.processors
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
          kwargs:
              fields_group: label
    label: ["Ref($close, -1) / $close - 1"]

port_analysis_config: &port_analysis_config
    strategy:
        class: SimpleSignalStrategy
        module_path: backtest.qlib_custom.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
    backtest:
        start_time: 2019-01-01
        end_time: 2023-03-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            deal_price: close
            open_cost: 0
            close_cost: 0
            min_cost: 0
task:
    model:
        class: GRU
        module_path: qlib.contrib.model.pytorch_gru
        kwargs:
            d_feat: 4
            hidden_size: 64
            num_layers: 2
            dropout: 0.0
            n_epochs: 200
            lr: 1e-3
            early_stop: 20
            batch_size: 64
            metric: loss
            loss: mse
            GPU: 0
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: VixHandler
                module_path: backtest.qlib_custom.data_handler
                kwargs: *data_handler_config
            segments:
                train: [2005-12-20, 2011-12-31]
                valid: [2012-01-01, 2018-12-31]
                test: [2019-01-01, 2023-08-01]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: StandalonePortAnaRecord
          module_path: backtest.qlib_custom.record
          kwargs: 
            config: *port_analysis_config
