artifact_uri: file:C:\Users\63153\smangj_program\vix_option\mlruns/4/ee16729a846348ceacbe20aedc76652f/artifacts
end_time: null
entry_point_name: ''
experiment_id: '4'
lifecycle_stage: active
run_id: ee16729a846348ceacbe20aedc76652f
run_name: mlflow_recorder
run_uuid: ee16729a846348ceacbe20aedc76652f
source_name: ''
source_type: 4
source_version: ''
start_time: 1683770305193
status: 1
tags: []
user_id: '63153'
