qlib_init:
    provider_uri: "data/qlib_data"
    region: cn
    exp_manager:
        class: "MLflowExpManager"
        module_path: "qlib.workflow.expm"
        kwargs:
            uri: "databricks"
            default_exp_name: "Experiment"
experiment_name: "Fix_GroupVixHandler20230711_JiaQiRecord_test"
market: &market trable
benchmark: &benchmark TLT
roll_config:
    step: 20
    rolling_type: "expanding"
    horizon: 0
data_handler_config: &data_handler_config
    start_time: 2005-12-20
    end_time: 2022-08-15
    fit_start_time: 2005-12-20
    fit_end_time: 2022-08-15
    instruments: *market
    infer_processors: []
    learn_processors:
        - class: DropnaProcessor
          kwargs:
              fields_group: feature
        - class: DropnaLabel
    label: ["Ref($close, -1) / $close - 1"]
port_analysis_config: &port_analysis_config
    backtest:
        start_time: 2006-10-01
        end_time: 2022-12-15
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            deal_price: close
            open_cost: 0
            close_cost: 0
            min_cost: 0
task:
    - model:
        class: SmLinearModel
        module_path: backtest.qlib_custom.model
        kwargs:
            estimator: ols
            fit_intercept: 1
      dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: GroupVixHandler20230711
                module_path: backtest.qlib_custom.data_handler
                kwargs: *data_handler_config
            segments:
                train: [2005-12-20, 2006-06-30]
                valid: [2006-07-01, 2006-09-30]
                test: [2006-10-01, 2006-12-31]
      record:
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: True
            ann_scaler: 252
        - class: JiaQiRecord
          module_path: backtest.qlib_custom.record
          kwargs:
            config: *port_analysis_config
      name: "linear"
    - model:
        class: XgbFix
        module_path: backtest.qlib_custom.model
        kwargs:
            eval_metric: rmse
            colsample_bytree: 0.819
            eta: 0.0421
            n_estimators: 647
            min_child_weight: 1.376
            max_depth: 20
            subsample: 0.625784
            early_stopping_rounds: 30
      dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: GroupVixHandler20230711
                module_path: backtest.qlib_custom.data_handler
                kwargs: *data_handler_config
            segments:
                train: [2005-12-20, 2010-06-30]
                valid: [2010-07-01, 2010-12-31]
                test: [2011-01-01, 2011-01-31]
      record:
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: True
            ann_scaler: 252
        - class: JiaQiRecord
          module_path: backtest.qlib_custom.record
          kwargs:
            config: *port_analysis_config
      name: "XGB"
    - model:
        class: GRU
        module_path: qlib.contrib.model.pytorch_gru_ts
        kwargs:
            d_feat: 88
            hidden_size: 128
            num_layers: 3
            dropout: 0.0
            n_epochs: 20
            lr: 1e-3
            early_stop: 15
            batch_size: 128
            metric: loss
            loss: mse
            n_jobs: 0
            GPU: 0
      dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            step_len: 5
            handler:
                class: GroupVixHandler20230711
                module_path: backtest.qlib_custom.data_handler
                kwargs: *data_handler_config
            segments:
                train: [2005-12-20, 2006-06-30]
                valid: [2006-07-01, 2006-09-30]
                test: [2006-10-01, 2006-12-31]
      record:
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: True
            ann_scaler: 252
        - class: JiaQiRecord
          module_path: backtest.qlib_custom.record
          kwargs:
            config: *port_analysis_config
      name: "GRU"

