artifact_location: file:C:\Users\63153\smangj_program\vix_option\mlruns_test/8
creation_time: 1690343023127
experiment_id: '8'
last_update_time: 1690343023127
lifecycle_stage: active
name: GRU_GroupVixHandler20230711_LongShortBacktestRecord
