artifact_uri: file:C:\Users\63153\smangj_program\vix_option\mlruns_test\8\084e905ffbf34e69b74f2efc2cca2afb\artifacts
end_time: 1690343023369
entry_point_name: ''
experiment_id: '8'
lifecycle_stage: active
run_id: 084e905ffbf34e69b74f2efc2cca2afb
run_name: mlflow_recorder
run_uuid: 084e905ffbf34e69b74f2efc2cca2afb
source_name: ''
source_type: 4
source_version: ''
start_time: 1690343023214
status: 3
tags: []
user_id: root
