qlib_init:
    provider_uri: "data/qlib_data"
    region: cn
    exp_manager:
        class: "MLflowExpManager"
        module_path: "qlib.workflow.expm"
        kwargs:
            uri: "http://127.0.0.1:5001"
            default_exp_name: "Experiment"
market: &market trable
experiment_name: TCN_optuna_GroupVixHandler
roll_config:
    step: [5, 20, 60]
    rolling_type: "expanding"
    horizon: 0
data_handler_config: &data_handler_config
    start_time: 2005-12-20
    end_time: 2022-08-15
    fit_start_time: 2005-12-20
    fit_end_time: 2022-08-15
    instruments: *market
    infer_processors: []
    learn_processors:
        - class: DropnaProcessor
          kwargs:
              fields_group: feature
        - class: DropnaLabel
    label: ["Ref($close, -1) / $close - 1"]

task:
    model:
       class: TCN
       module_path: qlib.contrib.model.pytorch_tcn_ts
       kwargs:
           d_feat: 5
           hidden_size: 128
           num_layers: 3
           dropout: [0.0, 0.3]
           n_epochs: 20
           lr: [1e-3, 1e-2, 1e-1]
           early_stop: 15
           batch_size: 256
           metric: loss
           loss: mse
           n_jobs: 0
           GPU: 0
    dataset:
        class: TSDatasetH
        module_path: qlib.data.dataset
        kwargs:
            step_len: 5
            handler:
                class: GroupVixHandler
                module_path: backtest.qlib_custom.data_handler
                kwargs: *data_handler_config
            segments:
                train: [2005-12-20, 2010-06-30]
                valid: [2010-07-01, 2010-12-31]
                test: [2011-01-01, 2022-08-15]
    record:
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp

